name = "420blazin-seo"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "BEAST_SEO"
id = "36c1eaef07ad4d049b0001a6a353fabc"

[[routes]]
pattern = "420blazin.com/*"
zone_name = "420blazin.com"

[[routes]]
pattern = "www.420blazin.com/*"
zone_name = "420blazin.com"
