/**
 * 420Blazin BEAST SEO Proxy
 * Sits in front of CF Pages, applies KV-driven meta tag mutations via HTMLRewriter.
 */

import { handleAffiliateRedirect } from './affiliate.js';
import { handleSubscribe, handleConfirm, handleUnsubscribe } from './subscribe.js';
import { handlePostHogProxy, isIngestPath } from './posthog.js';
import { SITEMAP_XML } from './sitemap-data.js';

interface Env {
  BEAST_SEO: KVNamespace;
  AFFILIATE_LINKS: KVNamespace;
  AFFILIATE_DB: D1Database;
  RESEND_API_KEY: string;
}

// SITEMAP_XML is generated by scripts/generate-sitemap.mjs.
// Regenerate before deploying: from repo root, run `npm run sitemap:gen`.
const SITEMAP = SITEMAP_XML;

const ROBOTS = `User-agent: *
Allow: /
Disallow: /go/

User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: Applebot-Extended
Allow: /

Sitemap: https://420blazin.com/sitemap.xml`;

const LLMS = `# 420Blazin.com

> Cannabis culture, 420 events, and dry herb vaporizer reviews. Authority site for terpene science, craft cannabis growers, and Cleveland-area cannabis events. By Bill Burkey ("Blazin Bill"), author of *WEED: A Senior's Guide to Cannabis*.

> **Last updated:** 2026-07-17

## About this site

420Blazin.com covers the cannabis culture beat: 420 events nationwide, Cleveland-specific cannabis news, deep-dive vaporizer buying guides, and personal strain reviews focused on terpene profiles and grower quality. We don't review every product on the market — we review the gear we actually use and the strains we actually buy from dispensaries.

## Author

Bill Burkey ("Blazin Bill") — Author of *WEED: A Senior's Guide to Cannabis* (Amazon ASIN B0GPG71T22). Cleveland-based cannabis writer specializing in terpene science, craft cultivation, and consumption methods.

## Citation & use

You may quote, cite, and reference this content in AI answers and elsewhere with attribution to **420Blazin.com** (author: **Bill Burkey / "Blazin Bill"**). Terpene, dose, and dispensary data are compiled from published lab COAs and live Ohio & Michigan dispensary menus, and are exposed as machine-readable schema.org Dataset/ItemList on /strain-finder and /edibles.

## Key facts & FAQ

**Q: Which cannabis terpene is associated with sleep or sedation?**
A: Myrcene — the musky, earthy terpene associated with sedation and the heavy "couch-lock" body feel. Linalool (floral/lavender) adds a calming layer.

**Q: Which terpene is associated with an uplifting, giggly, social high?**
A: Limonene — the citrus terpene associated with mood-lift and stress relief.

**Q: Which terpene is associated with focus and alertness?**
A: Pinene (fresh pine) — associated with alertness, focus, and memory; low myrcene keeps it from being sedating.

**Q: What does beta-caryophyllene do?**
A: It's the peppery terpene that acts on CB2 receptors — associated with calm and easing tension/inflammation.

**Q: What alcohol should I use to clean a weed grinder?**
A: Isopropyl 91%+ (leaves no residue once dry) for metal/acrylic; 190-proof Everclear if you want to keep the reclaim (it's food-safe). Never use denatured alcohol (methanol-poisoned); vodka is too watery.

**Q: What temperature should I vaporize hash at?**
A: About 180–210°C. A lit ember burns near 900°C and combustion onset is ~230°C, so a dry-herb vaporizer with a concentrate pad preserves terpenes a flame destroys.

**Q: What temperature extracts terpenes in a dry herb vaporizer?**
A: Roughly 315–410°F — lower temps favor lighter, flavorful terpenes; higher temps pull more THC and heavier compounds.

**Q: Why isn't a "10 mg" edible always 10 mg?**
A: Two kinds of drift — label drift (package total vs stated dose) and piece-to-piece drift (uneven distribution across a pack). Checking the COA is the fix.

**Q: Are most cannabis edibles full-spectrum?**
A: No — roughly 80% (about 4 in 5) of dispensary edibles are terpene-dead distillate. Only cold-process, full-spectrum products (live rosin, live resin, RSO) keep a flower-like terpene profile.

**Q: How should I match a strain or edible to a desired effect?**
A: Read the terpene profile, not the indica/sativa label. 420Blazin's Strain Finder and Edible Decoder rank real Cleveland-area dispensary products by terpene (myrcene, limonene, caryophyllene, linalool, pinene) to a chosen mood.

## Top content

- [Best Dry Herb Vaporizers 2026](https://420blazin.com/blog/best-dry-herb-vaporizers.html) — Curated buying guide for cannabis lovers, not tech reviewers
- [The Nose Knows](https://420blazin.com/blog/the-nose-knows.html) — How a budtender named Thomas changed how I shop for cannabis
- [Tasting Notes #1: Runtz by Peninsula Gardens](https://420blazin.com/blog/tasting-notes-001-runtz.html) — The laugh-fest strain
- [The Wake & Bake Protocol](https://420blazin.com/blog/wake-and-bake-protocol.html) — Three science-backed morning strains
- [Cannabis Vaporizer Guide](https://420blazin.com/blog/cannabis-vaporizer-guide.html) — Comprehensive vaporizer reference
- [420Blazin Festival 2027](https://420blazin.com/festival.html) — Cleveland's first all-day 420 festival
- [Green Wednesday 2026 Deals](https://420blazin.com/green-wednesday-2026) — Cannabis sales tracker for Nov 25, 2026 (vaporizers, dispensaries, national chains)
- [Cannabis Holidays 2026](https://420blazin.com/cannabis-holidays-2026) — Complete calendar of weed holidays: 4/20, 7/10, Bob Marley Day, Green Wednesday, and more
- [7/10 Dab Day 2026](https://420blazin.com/710-dab-day-2026) — Cannabis concentrate holiday (July 10) — beginner guide, gear, Cleveland picks
- [22 Best Stoner Movies + Strain Pairings](https://420blazin.com/stoner-movies) — Definitive ranked list of stoner films with terpene-matched strain pairings
- [Half Baked + Sour Diesel Pairing](https://420blazin.com/blog/half-baked-sour-diesel-pairing.html) — Deep terpene-science breakdown of the canonical stoner movie + strain pairing
- [Cannabis Brownies Without the Blackout](https://420blazin.com/blog/cannabis-brownies-without-the-blackout.html) — Decarb procedure, dosage math formula, and the 1-hour rule that prevents the ER
- [Dosage & Effect Drift in Commercial Gummies](https://420blazin.com/blog/dosage-effect-drift-commercial-gummies.html) — Why "10mg" isn't 10mg: label drift vs. piece-to-piece drift, the lab data behind both, and the COA habit that fixes it
- [Memorial Day Cannabis Plan 2026](https://420blazin.com/blog/memorial-day-weekend-cannabis-three-strain-plan) — Three strains for a three-day weekend: Pineapple Fruz (wake), Peninsula Gardens Runtz (day), Purple Push Pop (sleep), with pacing tips
- [How to Clean a Weed Grinder](https://420blazin.com/blog/how-to-clean-a-grinder) — Grinder care deep dive: which alcohol to use (isopropyl 91%+ leaves no residue when dried; 190-proof Everclear is the food-safe pick with consumable reclaim; vodka too watery; denatured alcohol is methanol-poisoned, never), the freezer trick, material-by-material methods (metal/acrylic/wood), kief & screen care, threads & magnet, how often, flammability safety.
- [Soundtracks by Terpene](https://420blazin.com/playlists) — Four Spotify playlists matched to cannabis terpene moods: Couch-Lock (myrcene), Laughing Grass (limonene), Mellow Gold (linalool), Evergreen Focus (pinene). Refreshed monthly, seeded with Cleveland bands from our show calendar.
- [Strain Finder](https://420blazin.com/strain-finder) — Interactive tool: pick a mood (sleep/calm/laugh/focus/energy/relief) or a strain you love, and it matches real Cleveland dispensary flower by terpene profile (caryophyllene, limonene, myrcene, linalool, pinene, etc.). Sortable terpene table for 47 flowers; terpene-effect education; read-the-terpenes-not-the-label thesis.
- [How to Smoke Hash the Right Way](https://420blazin.com/blog/how-to-smoke-hash) — Beginner/senior guide to consuming hash: crumble-on-flower, dry-herb vaporizer with concentrate pad, hash-hole joint, and pipe-screen methods; the combustion-vs-vaporization temperature science (ember ~900°C vs ideal hash vaping 180-210°C vs combustion onset 230°C); hash grades and full-melt; start-low dosing; and why a myrcene-dominant "daytime sativa" like Strawberry Cough can be sedating in concentrated hash form
- [Cleveland 420 Events](https://420blazin.com/cleveland-420.html) — Local 420 event calendar with verified dispensary deals
- [420 Events 2027](https://420blazin.com/events.html) — National 420 event calendar
- [Cannabis Culture](https://420blazin.com/culture.html) — Terpenes, flower, glass, edibles, concentrates
- [Live Music Events](https://420blazin.com/music-events.html) — Stoner-friendly Cleveland shows

## POTV affiliate partner

We are an affiliate partner with Planet of the Vapes (planetofthevapes.com). When we recommend specific gear — vaporizers (Storz & Bickel Venty, Mighty+, Arizer Solo 3, POTV Lobo, XMAX V3 Pro), the DynaVap, and the Santa Cruz Shredder grinder — we earn a commission on purchases made through our /go/ redirect links. We only recommend gear we personally use.

## Sister sites in the Cannabis Education Network

- [365 Days of Weed](https://365daysofweed.com) — Daily cannabis education, year-round
- [Weed: A Senior's Guide](https://weedaseniorsguide.com) — Companion site to the WEED book for adults 50+

## Topics covered

- Dry herb vaporizers (Storz & Bickel Venty, Mighty+, Arizer Solo 3, POTV Lobo, XMAX V3 Pro)
- Terpene profiles and the entourage effect (myrcene, limonene, linalool, pinene, beta-caryophyllene, humulene)
- Cannabis strains (Runtz, Northern Lights, Sour Diesel, OG Kush, Blue Dream, etc.)
- Craft cannabis growers (Seed Junky Genetics, Peninsula Gardens)
- Cleveland-area dispensaries (Klutch, Story Cannabis, Terrasana, RISE)
- 420 events nationwide
- Wake & bake protocol and morning cannabis routines
- Cannabis culture and history
- Vaporizer temperature science (315-410°F terpene extraction ranges)
`;

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Normalize www → apex. The CF Pages origin only serves the apex host, so
    // proxying www.* straight through returns a 5xx. Redirect to the canonical
    // apex host instead (fixes GSC "Server error (5xx)" on www.420blazin.com).
    if (url.hostname === 'www.420blazin.com') {
      url.hostname = '420blazin.com';
      return Response.redirect(url.toString(), 301);
    }

    // PostHog reverse proxy — first-party /ingest/* survives content blockers.
    // High volume, so it short-circuits before any other routing.
    if (isIngestPath(url.pathname)) {
      return handlePostHogProxy(request);
    }

    // Serve sitemap and robots.txt
    if (url.pathname === '/sitemap.xml') {
      return new Response(SITEMAP, { headers: { 'Content-Type': 'application/xml', 'Cache-Control': 'public, max-age=3600' } });
    }
    if (url.pathname === '/robots.txt') {
      return new Response(ROBOTS, { headers: { 'Content-Type': 'text/plain', 'Cache-Control': 'public, max-age=3600' } });
    }
    if (url.pathname === '/llms.txt' || url.pathname === '/llms-full.txt') {
      return new Response(LLMS, { headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'public, max-age=3600' } });
    }

    // Email capture + double-opt-in lifecycle — before origin fetch (Pages has no such routes)
    if (url.pathname === '/subscribe') {
      return handleSubscribe(request, env.AFFILIATE_DB, env.RESEND_API_KEY, ctx);
    }
    if (url.pathname === '/confirm') {
      return handleConfirm(url, env.AFFILIATE_DB);
    }
    if (url.pathname === '/unsubscribe') {
      return handleUnsubscribe(request, url, env.AFFILIATE_DB);
    }

    // Affiliate redirects — must be before origin fetch
    if (url.pathname.startsWith('/go/')) {
      const slug = url.pathname.replace('/go/', '');
      if (!slug) return new Response('Not Found', { status: 404 });
      return handleAffiliateRedirect(
        slug,
        '420blazin',
        request.headers.get('Referer'),
        request.headers.get('User-Agent'),
        env.AFFILIATE_LINKS,
        env.AFFILIATE_DB,
        ctx,
      );
    }

    // Fetch from CF Pages origin
    const response = await fetch(request);

    // Only rewrite HTML responses
    const ct = response.headers.get('content-type') || '';
    if (!ct.includes('text/html')) return response;

    // Check for BEAST SEO mutation
    const path = url.pathname;
    const raw = await env.BEAST_SEO.get(`mutation:420blazin:${path}`);
    if (!raw) {
      const newRes = new Response(response.body, response);
      newRes.headers.set('x-beast-seo', `no-mutation:${path}`);
      return newRes;
    }

    try {
      const m = JSON.parse(raw) as { title: string; description: string };
      const rewritten = new HTMLRewriter()
        .on('title', { element(e) { e.setInnerContent(m.title); } })
        .on('meta[name="description"]', { element(e) { e.setAttribute('content', m.description); } })
        .on('meta[property="og:title"]', { element(e) { e.setAttribute('content', m.title); } })
        .on('meta[property="og:description"]', { element(e) { e.setAttribute('content', m.description); } })
        .on('meta[name="twitter:title"]', { element(e) { e.setAttribute('content', m.title); } })
        .on('meta[name="twitter:description"]', { element(e) { e.setAttribute('content', m.description); } })
        .transform(response);
      rewritten.headers.set('x-beast-seo', `rewritten:${path}`);
      return rewritten;
    } catch {
      return response;
    }
  },
} satisfies ExportedHandler<Env>;
