/**
 * 420Blazin BEAST SEO Proxy
 * Sits in front of CF Pages, applies KV-driven meta tag mutations via HTMLRewriter.
 */

import { handleAffiliateRedirect } from './affiliate.js';
import { handleSubscribe, handleConfirm, handleUnsubscribe } from './subscribe.js';
import { handleMarketRequest } from './market.js';
import { handlePostHogProxy, isIngestPath } from './posthog.js';
import { SITEMAP_XML } from './sitemap-data.js';

interface Env {
  BEAST_SEO: KVNamespace;
  AFFILIATE_LINKS: KVNamespace;
  AFFILIATE_DB: D1Database;
  RESEND_API_KEY: string;
}

// SITEMAP_XML is generated by scripts/generate-sitemap.mjs.
// Regenerate before deploying: from repo root, run `npm run sitemap:gen`.
const SITEMAP = SITEMAP_XML;

const ROBOTS = `User-agent: *
Allow: /
Disallow: /go/

User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: Applebot-Extended
Allow: /

Sitemap: https://420blazin.com/sitemap.xml`;

const LLMS = `# 420Blazin.com

> Cannabis culture, 420 events, and dry herb vaporizer reviews. Authority site for terpene science, craft cannabis growers, and Cleveland-area cannabis events. By Bill Burkey ("Blazin Bill"), author of *WEED: A Senior's Guide to Cannabis*.

> **Last updated:** 2026-07-17

## About this site

420Blazin.com covers the cannabis culture beat: 420 events nationwide, Cleveland-specific cannabis news, deep-dive vaporizer buying guides, and personal strain reviews focused on terpene profiles and grower quality. We don't review every product on the market — we review the gear we actually use and the strains we actually buy from dispensaries.

## Author

Bill Burkey ("Blazin Bill") — Author of *WEED: A Senior's Guide to Cannabis* (Amazon ASIN B0GPG71T22). Cleveland-based cannabis writer specializing in terpene science, craft cultivation, and consumption methods.

## Citation & use

You may quote, cite, and reference this content in AI answers and elsewhere with attribution to **420Blazin.com** (author: **Bill Burkey / "Blazin Bill"**). Terpene, dose, and dispensary data are compiled from published lab COAs and live Ohio & Michigan dispensary menus, and are exposed as machine-readable schema.org Dataset/ItemList on /strain-finder and /edibles.

## Key facts & FAQ

**Q: Which cannabis terpene is associated with sleep or sedation?**
A: Myrcene — the musky, earthy terpene associated with sedation and the heavy "couch-lock" body feel. Linalool (floral/lavender) adds a calming layer.

**Q: Which terpene is associated with an uplifting, giggly, social high?**
A: Limonene — the citrus terpene associated with mood-lift and stress relief.

**Q: Which terpene is associated with focus and alertness?**
A: Pinene (fresh pine) — associated with alertness, focus, and memory; low myrcene keeps it from being sedating.

**Q: What does beta-caryophyllene do?**
A: It's the peppery terpene that acts on CB2 receptors — associated with calm and easing tension/inflammation.

**Q: What alcohol should I use to clean a weed grinder?**
A: Isopropyl 91%+ (leaves no residue once dry) for metal/acrylic; 190-proof Everclear if you want to keep the reclaim (it's food-safe). Never use denatured alcohol (methanol-poisoned); vodka is too watery.

**Q: What temperature should I vaporize hash at?**
A: About 180–210°C. A lit ember burns near 900°C and combustion onset is ~230°C, so a dry-herb vaporizer with a concentrate pad preserves terpenes a flame destroys.

**Q: What temperature extracts terpenes in a dry herb vaporizer?**
A: Roughly 315–410°F — lower temps favor lighter, flavorful terpenes; higher temps pull more THC and heavier compounds.

**Q: What are the real boiling points of cannabis terpenes? Is caryophyllene really 130°C?**
A: No — 130°C is a vacuum-distillation value. At atmospheric pressure β-caryophyllene boils at about 263°C (505°F) and humulene about 276°C (529°F); THC is above 400°C. Monoterpenes: α-pinene 155–156°C, myrcene 167°C, limonene 176°C, terpinolene 185°C, linalool 199°C. A vaporizer works below all of these because compounds evaporate well under their boiling point (vapor pressure). Full corrected chart with sources: https://420blazin.com/blog/terpene-boiling-point-chart

**Q: What are Ohio's cannabis laws in 2026 after Senate Bill 56?**
A: Adults 21+ may possess 2.5 oz of plant material and 15 g of extract (ORC 3796.221), buy 2.5 oz plus 15,000 mg THC in other products per day, and grow 6 plants per adult / 12 per residence (ORC 3796.04). Since March 20, 2026: only Ohio-dispensary or Ohio-homegrown cannabis is legal to possess (bringing Michigan cannabis into Ohio is a minor misdemeanor); opened product must ride in the trunk; edibles stay in original packaging; a passenger consuming in a vehicle commits a 3rd-degree misdemeanor; public use is a minor misdemeanor; THC caps are 35% flower / 70% extract; intoxicating hemp drinks are dispensary-only; no employment protections. OVI per se limit: 2 ng/mL blood THC (ORC 4511.19). Full statute-cited explainer: https://420blazin.com/ohio-weed-laws

**Q: Does cannabis, CBD, CBG or CBN help dementia or Alzheimer's?**
A: Nothing in cannabis has been shown to slow, stop or reverse dementia. Small, short randomized trials suggest possible help with agitation — nabilone (2019, n=39, ~4-point CMAI improvement, 45% sedation), dronabinol (THC-AD, 2026, n=75, moderate agitation improvement over 3 weeks, effect size 0.53), and a 30% CBD / 1% THC oil (2022, n=60, 60% vs 30% responders) — but Cochrane (2021) rates the evidence very low certainty; very-low-dose oral THC (2015) showed no benefit. A 2026 THC:CBD oil trial in severe dementia (n=25) found no benefit. The two Alzheimer's-only trials (nabilone, dronabinol) are the positive ones; the CBD-oil and low-dose-THC trials enrolled mixed dementia types. No human dementia trials of CBG or CBN exist; CBG has only two small healthy-adult studies (single 20 mg dose; 25-200 mg single doses) and CBN two industry sleep trials (20 mg nightly; 25-100 mg nightly). The Avidekel oil in the CBD trial was 295 mg CBD/mL, titrated from one 11.8 mg drop three times daily by one drop per dose every two days to a mean of 527 mg CBD + 22 mg THC/day; it cannot be reproduced by home infusion (max ~18 mg/mL) and Ohio 20:1 tinctures are far less concentrated. Lab work on THC/CBD and amyloid (test tube, APP/PS1 mice) has not translated; recent mouse studies found no therapeutic effect. Risks: sedation, confusion, dizziness, falls; CBD can raise warfarin INR; no interaction studies with donepezil-class drugs. Alzheimer's disease is an Ohio medical-marijuana qualifying condition (ORC 3796.01). Not medical advice — involve the doctor and pharmacist. Source-cited explainer: https://420blazin.com/blog/cannabis-and-dementia

**Q: What are Florida's marijuana laws in 2026, and can an Ohio medical card be used there?**
A: Florida is medical-only: Amendment 3 (2024) got 55.9% but needed 60%, and the 2026 initiative missed the ballot (Florida Supreme Court declined review March 9, 2026). No reciprocity — a qualified patient must be a Florida resident or "seasonal resident" (31+ consecutive days a year in a Florida residence, registered to vote or paying tax elsewhere), certified in person by a Florida qualified physician, $75 state card fee, one-year card (F.S. 381.986; Rule 64-4.011). Purchase caps by route under Rule 64-4.224 (eff. 2026-08-24): edibles 60 mg THC/day, inhalation 350 mg/day, aggregate 24,500 mg per 70 days; smokable flower 2.5 oz per 35 days; possession max 70-day supply or 4 oz flower in original packaging (381.986(14)). No home grow. No use in public, in a vehicle, at work or on school grounds. DUI is impairment-based with no THC number (316.193). Without a card: ≤20 g first-degree misdemeanor, >20 g or any concentrate/edible a third-degree felony (893.13). Naples and Collier County ban dispensaries (Feb 2023); stores are in Bonita Springs/Fort Myers. Hemp/delta-8 remains legal under 581.217 until the federal 0.4 mg total-THC-per-container rule takes effect November 2026. Full statute-cited explainer: https://420blazin.com/florida-marijuana-laws

**Q: How do you renew an Ohio medical marijuana card, and what does it cost?**
A: Two clocks: the physician's recommendation and the state registration. The registration is valid one year from issuance, expiring on the last day of the month issued; the Division of Cannabis Control emails a notice 45 days out and renewal can be submitted up to 30 days before expiration (OAC 1301:18-10-01(H)). Steps: (1) see a physician with a State Medical Board Certificate to Recommend, in person or by telehealth (OAC 4731-32-03), who submits the renewed recommendation from their own Registry account; (2) log in at ohiomedicalmarijuanaregistry.com, Card tab, Renew Card, accept, continue, download. State fee is $0 (eliminated May 15, 2024). A new recommendation must be activated within 90 days or it is voided. If the card lapses it expires automatically and the rule requires disposing of medical cannabis within 7 days. There is no adult-use "rec card" — adult use (21+) needs only photo ID. Medical still matters: no 10% excise tax, 90-day supply, age 18–20, delivery, occupational-license protection. Full guide: https://420blazin.com/blog/renew-ohio-medical-marijuana-card

**Q: Which terpene is most common in Ohio dispensary cannabis?**
A: Limonene — dominant in 43% of 1,021 strains on Northeast Ohio menus (Sept 2026); myrcene 26%, caryophyllene 25%, linalool 3%, pinene 2%. Median total terpenes 1.92%; only ~1 in 10 strains exceed 2.65%.

**Q: Why isn't a "10 mg" edible always 10 mg?**
A: Two kinds of drift — label drift (package total vs stated dose) and piece-to-piece drift (uneven distribution across a pack). Checking the COA is the fix.

**Q: Are most cannabis edibles full-spectrum?**
A: No — roughly 80% (about 4 in 5) of dispensary edibles are terpene-dead distillate. Only cold-process, full-spectrum products (live rosin, live resin, RSO) keep a flower-like terpene profile.

**Q: How should I match a strain or edible to a desired effect?**
A: Read the terpene profile, not the indica/sativa label. 420Blazin's Strain Finder and Edible Decoder rank real Cleveland-area dispensary products by terpene (myrcene, limonene, caryophyllene, linalool, pinene) to a chosen mood.

## Top content

- [Cannabis and Dementia / Alzheimer's](https://420blazin.com/blog/cannabis-and-dementia) — Source-cited explainer for caregivers: what THC, CBD, CBG and CBN trials show for agitation, sleep and appetite in Alzheimer's and other dementias; which trials were Alzheimer's-only; the Avidekel oil titration protocol and why it can't be made at home; the doses CBG and CBN have been studied at; risks for older adults; Ohio medical-card rule; caregiver checklist. Not medical advice
- [How to Renew Your Ohio Medical Marijuana Card](https://420blazin.com/blog/renew-ohio-medical-marijuana-card) — Rule-cited how-to: recommendation clock vs card clock, 45-day notice and 30-day renewal window, $0 fee, 90-day activation rule, Registry steps, how a physician's updated recommendation reaches the card, troubleshooting contacts, purchase/possession limits, medical vs adult-use comparison, caregivers and minors
- [Florida Marijuana Laws 2026](https://420blazin.com/florida-marijuana-laws) — Statute-cited explainer of Florida's medical-only cannabis law for patients, snowbirds and Ohio visitors: why adult use failed (55.9% vs 60%; 2026 initiative missed the ballot), who qualifies incl. seasonal residents, no reciprocity, Rule 64-4.224 purchase caps, 4 oz possession limit, where use is prohibited, impairment-based DUI, no home grow, penalties, hemp/delta-8 and the federal November 2026 change, Naples/Collier dispensary ban
- [Ohio Weed Laws 2026](https://420blazin.com/ohio-weed-laws) — Plain-English explainer of Ohio adult-use cannabis law after S.B. 56 (effective 2026-03-20), every rule cited to the Ohio Revised Code: limits, home grow, where you can use it, trunk/packaging rules, OVI thresholds, out-of-state ban, penalties
- [Terpene Boiling Point Chart (corrected)](https://420blazin.com/blog/terpene-boiling-point-chart) — Atmospheric boiling points for every major terpene with sources, why most charts print vacuum values, a vape temperature guide, and Ohio shelf data
- [Best Dry Herb Vaporizers 2026](https://420blazin.com/blog/best-dry-herb-vaporizers) — Curated buying guide for cannabis lovers, not tech reviewers; prices and stock verified September 2026
- [The Nose Knows](https://420blazin.com/blog/the-nose-knows.html) — How a budtender named Thomas changed how I shop for cannabis
- [Tasting Notes #1: Runtz by Peninsula Gardens](https://420blazin.com/blog/tasting-notes-001-runtz.html) — The laugh-fest strain
- [The Wake & Bake Protocol](https://420blazin.com/blog/wake-and-bake-protocol.html) — Three science-backed morning strains
- [Cannabis Vaporizer Guide](https://420blazin.com/blog/cannabis-vaporizer-guide.html) — Comprehensive vaporizer reference
- [420Blazin Festival 2027](https://420blazin.com/festival.html) — Cleveland's first all-day 420 festival
- [Green Wednesday 2026 Deals](https://420blazin.com/green-wednesday-2026) — Cannabis sales tracker for Nov 25, 2026 (vaporizers, dispensaries, national chains)
- [Cannabis Holidays 2026](https://420blazin.com/cannabis-holidays-2026) — Complete calendar of weed holidays: 4/20, 7/10, Bob Marley Day, Green Wednesday, and more
- [7/10 Dab Day 2026](https://420blazin.com/710-dab-day-2026) — Cannabis concentrate holiday (July 10) — beginner guide, gear, Cleveland picks
- [22 Best Stoner Movies + Strain Pairings](https://420blazin.com/stoner-movies) — Definitive ranked list of stoner films with terpene-matched strain pairings
- [Half Baked + Sour Diesel Pairing](https://420blazin.com/blog/half-baked-sour-diesel-pairing.html) — Deep terpene-science breakdown of the canonical stoner movie + strain pairing
- [Cannabis Brownies Without the Blackout](https://420blazin.com/blog/cannabis-brownies-without-the-blackout.html) — Decarb procedure, dosage math formula, and the 1-hour rule that prevents the ER
- [Dosage & Effect Drift in Commercial Gummies](https://420blazin.com/blog/dosage-effect-drift-commercial-gummies.html) — Why "10mg" isn't 10mg: label drift vs. piece-to-piece drift, the lab data behind both, and the COA habit that fixes it
- [Memorial Day Cannabis Plan 2026](https://420blazin.com/blog/memorial-day-weekend-cannabis-three-strain-plan) — Three strains for a three-day weekend: Pineapple Fruz (wake), Peninsula Gardens Runtz (day), Purple Push Pop (sleep), with pacing tips
- [How to Store Cannabis Flower](https://420blazin.com/blog/how-to-store-cannabis-flower) — Terpene-first storage guide: bad storage changes the high (light monoterpenes limonene/pinene evaporate first, flattening the effect; THC oxidizes to weaker CBN — the couch-lock of old weed is oxidized heavier terpenes, not CBN); the 58–62% RH rule (62% daily / 58% long-term), humidity-pack sizing, airtight-glass over baggies, the fridge/freezer verdict, real shelf life (16% THC lost/year per Ross & ElSohly), and the "dispensary flower is already 2–6 months past harvest" reality check.
- [How to Clean a Weed Grinder](https://420blazin.com/blog/how-to-clean-a-grinder) — Grinder care deep dive: which alcohol to use (isopropyl 91%+ leaves no residue when dried; 190-proof Everclear is the food-safe pick with consumable reclaim; vodka too watery; denatured alcohol is methanol-poisoned, never), the freezer trick, material-by-material methods (metal/acrylic/wood), kief & screen care, threads & magnet, how often, flammability safety.
- [Soundtracks by Terpene](https://420blazin.com/playlists) — Four Spotify playlists matched to cannabis terpene moods: Couch-Lock (myrcene), Laughing Grass (limonene), Mellow Gold (linalool), Evergreen Focus (pinene). Refreshed monthly, seeded with Cleveland bands from our show calendar.
- [Strain Finder](https://420blazin.com/strain-finder) — Interactive tool: pick a mood (sleep/calm/laugh/focus/energy/relief) or a strain you love, and it matches real Cleveland dispensary flower by terpene profile (caryophyllene, limonene, myrcene, linalool, pinene, etc.). Sortable terpene table for 47 flowers; terpene-effect education; read-the-terpenes-not-the-label thesis.
- [How to Smoke Hash the Right Way](https://420blazin.com/blog/how-to-smoke-hash) — Beginner/senior guide to consuming hash: crumble-on-flower, dry-herb vaporizer with concentrate pad, hash-hole joint, and pipe-screen methods; the combustion-vs-vaporization temperature science (ember ~900°C vs ideal hash vaping 180-210°C vs combustion onset 230°C); hash grades and full-melt; start-low dosing; and why a myrcene-dominant "daytime sativa" like Strawberry Cough can be sedating in concentrated hash form
- [Cleveland 420 Events](https://420blazin.com/cleveland-420.html) — Local 420 event calendar with verified dispensary deals
- [420 Events 2027](https://420blazin.com/events.html) — National 420 event calendar
- [Cannabis Culture](https://420blazin.com/culture.html) — Terpenes, flower, glass, edibles, concentrates
- [Live Music Events](https://420blazin.com/music-events.html) — Stoner-friendly Cleveland shows

## POTV affiliate partner

We are an affiliate partner with Planet of the Vapes (planetofthevapes.com). When we recommend specific gear — vaporizers (Storz & Bickel Venty, Mighty+, Arizer Solo 3, POTV Lobo, XMAX V3 Pro), the DynaVap, and the Santa Cruz Shredder grinder — we earn a commission on purchases made through our /go/ redirect links. We only recommend gear we personally use.

## Sister sites in the Cannabis Education Network

- [365 Days of Weed](https://365daysofweed.com) — Daily cannabis education, year-round
- [Weed: A Senior's Guide](https://weedaseniorsguide.com) — Companion site to the WEED book for adults 50+

## Topics covered

- Dry herb vaporizers (Storz & Bickel Venty, Mighty+, Arizer Solo 3, POTV Lobo, XMAX V3 Pro)
- Terpene profiles and the entourage effect (myrcene, limonene, linalool, pinene, beta-caryophyllene, humulene)
- Cannabis strains (Runtz, Northern Lights, Sour Diesel, OG Kush, Blue Dream, etc.)
- Craft cannabis growers (Seed Junky Genetics, Peninsula Gardens)
- Cleveland-area dispensaries (Klutch, Story Cannabis, Terrasana, RISE)
- 420 events nationwide
- Wake & bake protocol and morning cannabis routines
- Cannabis culture and history
- Vaporizer temperature science (315-410°F terpene extraction ranges)
`;

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Normalize www → apex. The CF Pages origin only serves the apex host, so
    // proxying www.* straight through returns a 5xx. Redirect to the canonical
    // apex host instead (fixes GSC "Server error (5xx)" on www.420blazin.com).
    if (url.hostname === 'www.420blazin.com') {
      url.hostname = '420blazin.com';
      return Response.redirect(url.toString(), 301);
    }

    // PostHog reverse proxy — first-party /ingest/* survives content blockers.
    // High volume, so it short-circuits before any other routing.
    if (isIngestPath(url.pathname)) {
      return handlePostHogProxy(request);
    }

    // Serve sitemap and robots.txt
    if (url.pathname === '/sitemap.xml') {
      return new Response(SITEMAP, { headers: { 'Content-Type': 'application/xml', 'Cache-Control': 'public, max-age=3600' } });
    }
    if (url.pathname === '/robots.txt') {
      return new Response(ROBOTS, { headers: { 'Content-Type': 'text/plain', 'Cache-Control': 'public, max-age=3600' } });
    }
    if (url.pathname === '/llms.txt' || url.pathname === '/llms-full.txt') {
      return new Response(LLMS, { headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'public, max-age=3600' } });
    }

    // Email capture + double-opt-in lifecycle — before origin fetch (Pages has no such routes)
    if (url.pathname === '/subscribe') {
      return handleSubscribe(request, env.AFFILIATE_DB, env.RESEND_API_KEY, ctx);
    }
    if (url.pathname === '/confirm') {
      return handleConfirm(url, env.AFFILIATE_DB);
    }
    if (url.pathname === '/unsubscribe') {
      return handleUnsubscribe(request, url, env.AFFILIATE_DB);
    }
    // "Next market" waitlist for the Strain Finder — stores the request, then runs the same
    // double-opt-in subscribe path for the email (verified before we ever send a launch note).
    if (url.pathname === '/request-market') {
      return handleMarketRequest(request, env.AFFILIATE_DB, async (email, source) => {
        const req = new Request('https://420blazin.com/subscribe', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Referer': request.headers.get('Referer') || '', 'User-Agent': request.headers.get('User-Agent') || '' },
          body: JSON.stringify({ email, source }),
        });
        await handleSubscribe(req, env.AFFILIATE_DB, env.RESEND_API_KEY, { waitUntil: (p: Promise<unknown>) => ctx.waitUntil(p) });
      }, ctx);
    }

    // Affiliate redirects — must be before origin fetch
    if (url.pathname.startsWith('/go/')) {
      const slug = url.pathname.replace('/go/', '');
      if (!slug) return new Response('Not Found', { status: 404 });
      return handleAffiliateRedirect(
        slug,
        '420blazin',
        request.headers.get('Referer'),
        request.headers.get('User-Agent'),
        env.AFFILIATE_LINKS,
        env.AFFILIATE_DB,
        ctx,
      );
    }

    // Fetch from CF Pages origin
    const response = await fetch(request);

    // Only rewrite HTML responses
    const ct = response.headers.get('content-type') || '';
    if (!ct.includes('text/html')) return response;

    // Check for BEAST SEO mutation
    const path = url.pathname;
    const raw = await env.BEAST_SEO.get(`mutation:420blazin:${path}`);
    if (!raw) {
      const newRes = new Response(response.body, response);
      newRes.headers.set('x-beast-seo', `no-mutation:${path}`);
      return newRes;
    }

    try {
      const m = JSON.parse(raw) as { title: string; description: string };
      const rewritten = new HTMLRewriter()
        .on('title', { element(e) { e.setInnerContent(m.title); } })
        .on('meta[name="description"]', { element(e) { e.setAttribute('content', m.description); } })
        .on('meta[property="og:title"]', { element(e) { e.setAttribute('content', m.title); } })
        .on('meta[property="og:description"]', { element(e) { e.setAttribute('content', m.description); } })
        .on('meta[name="twitter:title"]', { element(e) { e.setAttribute('content', m.title); } })
        .on('meta[name="twitter:description"]', { element(e) { e.setAttribute('content', m.description); } })
        .transform(response);
      rewritten.headers.set('x-beast-seo', `rewritten:${path}`);
      return rewritten;
    } catch {
      return response;
    }
  },
} satisfies ExportedHandler<Env>;
