// AUTO-GENERATED by scripts/generate-sitemap.mjs — DO NOT HAND-EDIT.
// Regenerate: `npm run sitemap:gen` from repo root, then `cd workers/seo-proxy && wrangler deploy`.
// Last generated: 2026-07-17 (43 URLs).

export interface SitemapEntry {
  loc: string;
  lastmod: string;
  changefreq: string;
  priority: string;
}

export const SITEMAP_ENTRIES: SitemapEntry[] = [
  {
    "loc": "https://420blazin.com/",
    "lastmod": "2026-06-28",
    "changefreq": "weekly",
    "priority": "1.0"
  },
  {
    "loc": "https://420blazin.com/404",
    "lastmod": "2026-06-12",
    "changefreq": "monthly",
    "priority": "0.6"
  },
  {
    "loc": "https://420blazin.com/710-dab-day-2026",
    "lastmod": "2026-06-28",
    "changefreq": "weekly",
    "priority": "0.9"
  },
  {
    "loc": "https://420blazin.com/about",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.5"
  },
  {
    "loc": "https://420blazin.com/blog",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/cannabis-holidays-2026",
    "lastmod": "2026-06-28",
    "changefreq": "weekly",
    "priority": "0.9"
  },
  {
    "loc": "https://420blazin.com/cleveland-420",
    "lastmod": "2026-06-28",
    "changefreq": "weekly",
    "priority": "0.9"
  },
  {
    "loc": "https://420blazin.com/contact",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.5"
  },
  {
    "loc": "https://420blazin.com/culture",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/culture-celebrations",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/culture-concentrates",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/culture-edibles",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/culture-flower",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/culture-glass",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/culture-plants",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/culture-rolling",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/culture-terpenes",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/edibles",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.6"
  },
  {
    "loc": "https://420blazin.com/events",
    "lastmod": "2026-06-28",
    "changefreq": "daily",
    "priority": "0.9"
  },
  {
    "loc": "https://420blazin.com/festival",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.9"
  },
  {
    "loc": "https://420blazin.com/green-wednesday-2026",
    "lastmod": "2026-06-28",
    "changefreq": "weekly",
    "priority": "0.9"
  },
  {
    "loc": "https://420blazin.com/heart-smart",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.6"
  },
  {
    "loc": "https://420blazin.com/jack-herer-day",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.6"
  },
  {
    "loc": "https://420blazin.com/merch",
    "lastmod": "2026-06-28",
    "changefreq": "weekly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/music-events",
    "lastmod": "2026-06-28",
    "changefreq": "daily",
    "priority": "0.9"
  },
  {
    "loc": "https://420blazin.com/newsletters/2026-06-issue-01",
    "lastmod": "2026-06-12",
    "changefreq": "monthly",
    "priority": "0.6"
  },
  {
    "loc": "https://420blazin.com/playlists",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.6"
  },
  {
    "loc": "https://420blazin.com/privacy",
    "lastmod": "2026-06-28",
    "changefreq": "yearly",
    "priority": "0.3"
  },
  {
    "loc": "https://420blazin.com/stoner-movies",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.8"
  },
  {
    "loc": "https://420blazin.com/strain-finder",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.6"
  },
  {
    "loc": "https://420blazin.com/terms",
    "lastmod": "2026-06-28",
    "changefreq": "yearly",
    "priority": "0.3"
  },
  {
    "loc": "https://420blazin.com/blog/best-dry-herb-vaporizers",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/cannabis-brownies-without-the-blackout",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/cannabis-vaporizer-guide",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/doctor-said-stop-smoking-keep-terpenes",
    "lastmod": "2026-06-27",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/dosage-effect-drift-commercial-gummies",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/half-baked-sour-diesel-pairing",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/how-to-clean-a-grinder",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/how-to-smoke-hash",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/memorial-day-weekend-cannabis-three-strain-plan",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/tasting-notes-001-runtz",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/the-nose-knows",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  },
  {
    "loc": "https://420blazin.com/blog/wake-and-bake-protocol",
    "lastmod": "2026-06-28",
    "changefreq": "monthly",
    "priority": "0.7"
  }
];

const xmlBody = SITEMAP_ENTRIES
  .map(e => `  <url><loc>${e.loc}</loc><lastmod>${e.lastmod}</lastmod><changefreq>${e.changefreq}</changefreq><priority>${e.priority}</priority></url>`)
  .join('\n');

export const SITEMAP_XML = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${xmlBody}
</urlset>`;
